### ISSUE TITLE
binding to python

### ISSUE THREAD

**Issue by arita37** [Netflix/vectorflow#4]
Any binding way from D language to Python ?

I only found this one.
https://code.dlang.org/packages/pyd

**Comment by rostyboost** [comment]
The package you linked to is one option. I haven't tried it though.
Internally, we have been testing SWIG bindings to different languages from a simple C API exposed from `vectorflow`, for model serving purposes. At this point, it is unlikely to be released.
Regarding model building/training and the programmatic API of model definitions, we don't have a plan to offer bindings either.
