### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by sergei3000** [Netflix/vectorflow#5]
I find the idea behind this project really cool. Are you planning to create Python API for Vectorflow? I think, that would be really great and would raise the number of users greatly.

**Comment by rostyboost** [comment]
Thank you. We don't have any plan/bandwidth at the moment to offer a Python API (see https://github.com/Netflix/vectorflow/issues/4 for more details) as the library heavily relies on some of D compile-time features to offer an efficient way to iterate over the data and feed it to the DAG.
However if you're familiar with [SWIG](http://www.swig.org/), it's fairly easy to offer a minimalist API. All you have to do is `extern(C)` or `extern(C++)` the basic `vectorflow` functions you need and let SWIG do the rest.
