### ISSUE TITLE
Examples won't run

### ISSUE THREAD

**Issue by sergei3000** [Netflix/vectorflow#6]
Hi!
Thanks for opening this instrument.
I am trying to make it work on my computer (Ubuntu 16.04 LTS).
I installed ldc and dub, and I cloned this repo.
I ran tests with `dub test`, which gave me the message "All unit tests have been run successfully."
Then I try to run examples as it is suggested in the readme:
`cd examples && ./compile_run.sh rcv1.d`
But this does not work. In my Terminal I get messages that variables 'evenCunks' and 'staticSort' are not found:
![image](https://user-images.githubusercontent.com/18502517/29754374-5d9e8c4e-8b8c-11e7-8f45-1490236d5d8b.png)

**Comment by henrygouk** [comment]
What version of LDC did you install?

**Comment by sergei3000** [comment]
It looks like it's 0.17.1.:
![image](https://user-images.githubusercontent.com/18502517/29754644-0e6e2804-8b92-11e7-8f2a-918690db6c01.png)

I installed it with `apt install ldc` like it is advised on this page:
https://github.com/ldc-developers/ldc#installation

UPDATE: Actually I don't quite remember how I installed it. I might have used the command `snap install --classic --edge ldc2` from readme.

**Comment by henrygouk** [comment]
LDC v0.17.1 uses quite an old version of the standard library, and evenChunks/staticSort are relatively recent additions. Try downloading v1.3.0 from the releases page of the LDC github repo---this should fix the problem.

**Comment by sergei3000** [comment]
It did fix the problem.
Thanks a lot!

**Comment by rostyboost** [comment]
Yep, your LDC was too old. Our [README](https://github.com/Netflix/vectorflow/blob/master/README.md) recommends an LDC version >= 1.1.1 but it looks like the `snap` command in the README installs a pretty old version. Will update the README. LDC github releases page is always the best distrib source for the compiler. Thanks!

**Comment by wilzbach** [comment]
> LDC github releases page is always the best distrib source for the compiler. Thanks!

FYI the official install script works for ldc too:

```
curl https://i.dlang.io | bash -s ldc
```

Or

```
curl https://i.dlang.io | bash -s ldc-1.3.0
```

**Comment by sergei3000** [comment]
@wilzbach thank you very much. I did not realize that.

**Comment by rostyboost** [comment]
Fixed with https://github.com/Netflix/vectorflow/pull/8.
